name: Publish to Pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'
  workflow_dispatch: # Permite disparar manualmente via aba Actions

jobs:
  publish:
    permissions:
      id-token: write # Obrigatório para autenticação OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Dart (for OIDC authentication)
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Publish to pub.dev
        run: flutter pub publish --force
